var lea = [

"Amazon All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 16 GB - Includes Special Offers, Magenta (BestBuy)",
"Kindle Oasis E-reader with Leather Charging Cover - Merlot, 6 High-Resolution Display (300 ppi), Wi-Fi - Includes Special Offers (BestBuy)",
"Amazon Kindle Lighted Leather Cover (Amazon)",
"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 32 GB - Includes Special Offers, Magenta (Amazon)",
"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 32 GB - Includes Special Offers, Magenta (BestBuy)",
"Fire HD 8 Tablet with Alexa, 8 HD Display, 32 GB, Tangerine - with Special Offers (BestBuy)",
"Amazon 5W USB Official OEM Charger and Power Adapter for Fire Tablets and Kindle eReaders (Amazon)",
"Amazon Kindle Fire Hd (3rd Generation) 8gb (BestBuy)",
"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Magenta (Amazon)",
"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Magenta (BestBuy)",
"Brand New Amazon Kindle Fire 16gb 7 Ips Display Tablet Wifi 16 Gb Blue (BestBuy)",
"Amazon Kindle Leather Cover (Amazon)",
"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16 GB, Green Kid-Proof Case (BestBuy)",
"Amazon Kindle Paperwhite - eBook reader - 4 GB - 6 monochrome Paperwhite - touchscreen - Wi-Fi - black (BestBuy)",
"Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers (BestBuy)",
"Amazon TV Stick (Amazon)",
"Kindle Paperwhite High Resolution (Amazon)",
"Fire Kid's Edition 16GB  (BestBuy)",
"Amazon Kindle Paperwhite (BestBuy)",
"Amazon Echo Fire Power Adapter (Amazon)",
"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Black (BestBuy)",
"Certified Refurbished Amazon Alexa Remote",
"Amazon Fire 16GB ,5th Gen, 2015 Release (BestBuy)",
"Amazon Fire 7 Tablet 8GB Black (BestBuy)",
"Echo White (BestBuy)",
"Voice Remote for Amazon Echo  (Amazon)",
"Amazon Echo w Alexa Voice Control Personal Assistant Bluetooth Speaker  (ebay)",
"Amazon PowerFast Official Charger eReaders (BestBuy)",
"Amazon PowerFast Official Charger eReaders (Amazon)",
"Standing Protective Case Generation C (Amazon)",
"Amazon Official Charger Adapter eReaders (Amazon)",
"Amazon Fire Tablet (BestBuy)",
"Amazon Tap Portable Bluetooth and Wi-Fi Speaker (BestBuy)",
"Amazon Fire TV 2015 Model (BestBuy)",
"Kindle Leather Display Latest Generation (Amazon)",
"Amazon Kindle Micro USB Cable Tablets (Amazon)",
"NEW Amazon Kindle Fire HD 9W Powerfast Adapter Charger Micro USB Angle Cable (eBay)",
"Amazon PowerFast Adapter Accelerated Charging (Amazon)"
           ]